name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/**'
      - ' build.gradle.kts'

permissions:
  checks: write

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [11]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Validate gradle-wrapper.jar
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java ${{ matrix.java-version }}
        users: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build
        run: ./gradlew build --info

      - name: Publish report
        users: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          job_name: Test report Kotlin/Native unit tests
